### ISSUE TITLE
Can this code be used for centernet test for coco?

### ISSUE THREAD

**Issue by YuqingWang1029** [lizhe960118/CenterNet#1]
I only see the train file for coco dataset

**Comment by lizhe960118** [comment]
This work is not completed, i will spend some time to modify it. 
You can learn to use mmdetection frist,  write you own code.
it can be used to test coco,  just use python test.py as mmdetection.

**Comment by YuqingWang1029** [comment]
> This work is not completed, i will spend some time to modify it.
> You can learn to use mmdetection frist, write you own code.
> it can be used to test coco, just use python test.py as mmdetection.

Ok, thanks for your reply.
