### ISSUE TITLE
results on the COCO or other dataset ?

### ISSUE THREAD

**Issue by Taotaoxu** [lizhe960118/CenterNet#2]
Well done ! Could you please show your experiment results on the COCO or other dataset ?

**Comment by lizhe960118** [comment]
i will update the results later.

**Comment by shuoshuoa** [comment]
I also want to know how it performs on coco.

**Comment by carry-xz** [comment]
nice, wish to see the result on coco !

**Comment by lfydegithub** [comment]
???
